import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
]

live_config_reload = true
# "window.dynamic_title" = false

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 16.5

# [font.bold]
# family = "FiraCode Nerd Font"
# style = "Bold"

# [font.bold_italic]
# family = "FiraCode Nerd Font"
# style = "Bold Italic"

# [font.italic]
# family = "FiraCode Nerd Font"
# style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# [[keyboard.bindings]]
# chars = "\u0002c"
# key = "T"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002x"
# key = "W"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002L"
# key = "L"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002\u0002"
# key = "Tab"
# mods = "Control"

# [mouse.hints]
# modifiers = "Command"

# [mouse.hints.launcher]
# program = "open"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
# dynamic_paddig = true
startup_mode = "maximized"
