#!/usr/bin/env bash
# pretty_path = f.path.replace(
#     os.path.expanduser("~"), "~", 1)

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/dev ~/ -mindepth 1 -maxdepth 1 -type d | sed -e "s|$HOME|~|" | sed -e "s|//|/|" | fzf --bind=enter:accept,ctrl-j:down,ctrl-k:up --margin=2%,2%,2%,2% --layout=reverse-list --border=none --info=inline --pointer=→ --color=dark,fg:white,info:white,bg+:black,hl:cyan,hl+:cyan,pointer:yellow,border:black)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# if  selected_name starts with _ then remove it
first_char=$(echo $selected_name | cut -c1)

if [[ $first_char == "_" ]]; then
	selected_name=$(echo $selected_name | cut -c2-)
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $selected_name -c $selected
	exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $selected -n "editor" -n "shell" -n "git"
fi

tmux switch-client -t $selected_name
