-- -- Set colorscheme
-- return {
-- 	-- 'Tsuzat/NeoSolarized.nvim',
-- 	-- 'nanotech/jellybeans.vim',
-- 	'rebelot/kanagawa.nvim',
-- 	name = 'kanagawa',
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 		require('kanagawa').setup({
-- 			compile = false, -- enable compiling the colorscheme
-- 			undercurl = true, -- enable undercurls
-- 			functionStyle = {},
-- 			keywordStyle = { italic = true },
-- 			statementStyle = { bold = true },
-- 			typeStyle = {},
-- 			dimInactive = false, -- dim inactive window `:h hl-NormalNC`
-- 			terminalColors = true, -- define vim.g.terminal_color_{0,17}
-- 			-- style = 'dark',
-- 			transparent = true,
-- 			commentStyle = { italic = true },
-- 			colors = {
-- 				theme = {
-- 					all = {
-- 						ui = {
-- 							bg_gutter = "none",
-- 							-- float = {
-- 							-- 	bg = "none"
-- 							-- }
-- 						}
-- 					}
-- 				}
-- 			},
-- 			overrides = function(colors)
-- 				local theme = colors.theme
-- 				-- vim.api.nvim_set_hl(0, 'LineNr', { bold = true })
-- 				vim.cmd([[
-- 					augroup VisualHighlight
-- 						autocmd!
-- 						autocmd VimEnter * hi Visual guibg='#3c3836'
-- 					augroup END
-- 				]])
--
-- 				return {
-- 					-- NormalFloat = { bg = "none" },
-- 					-- FloatBorder = { bg = "none" },
-- 					FloatTitle = { bg = "none" },
--
-- 					-- Save an hlgroup with dark background and dimmed foreground
-- 					-- so that you can use it where your still want darker windows.
-- 					-- E.g.: autocmd TermOpen * setlocal winhighlight=Normal:NormalDark
-- 					-- NormalDark = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
-- 					NormalDark = { fg = theme.ui.fg_dim, bg = 'none' },
--
-- 					-- Highlight the line of the current cursor
-- 					-- CursorLine = { bg = theme.ui.bg_dim },
-- 					-- CursorLineNr = { fg = theme.ui.special, bg = theme.ui.special },
-- 					-- LineNr = { fg = "#C0A36E", bg = "NONE" },
-- 					-- CursorLineNr = { fg = '#ffffff', bg = "NONE" },
-- 					-- LineNr = { fg = theme.ui.special, bg = theme.ui.bg_dim },
--
-- 					-- Popular plugins that open floats will link to NormalFloat by default;
-- 					-- set their background accordingly if you wish to keep them dark and borderless
-- 					LazyNormal = { bg = 'none', fg = theme.ui.fg_dim },
-- 					MasonNormal = { bg = 'none', fg = theme.ui.fg_dim },
--
-- 					-- Modern telescope
-- 					TelescopeTitle = { fg = theme.ui.special, bold = true },
-- 					TelescopePromptNormal = { bg = 'none' },
-- 					TelescopePromptBorder = { fg = theme.ui.bg_p1, bg = 'none' },
-- 					TelescopeResultsNormal = { fg = theme.ui.fg_dim, bg = 'none' },
-- 					TelescopeResultsBorder = { fg = theme.ui.bg_m1, bg = 'none' },
-- 					TelescopePreviewNormal = { bg = 'none' },
-- 					TelescopePreviewBorder = { bg = 'none', fg = theme.ui.bg_dim },
-- 					TelescopeMatching = { bold = true, fg = theme.ui.fg },
-- 					TelescopeSelection = { bg = theme.ui.bg_dim },
--
-- 					-- Dark completion menu
-- 					Pmenu = { fg = theme.ui.shade0, bg = 'none', blend = vim.o.pumblend }, -- add `blend = vim.o.pumblend` to enable transparency
-- 					PmenuSel = { fg = "NONE", bg = theme.ui.bg_dim },
-- 					PmenuSbar = { bg = theme.ui.bg_m1 },
-- 					PmenuThumb = { bg = theme.ui.bg_p2 },
--
-- 					FloatBorder = { bg = "NONE" },
-- 					NormalFloat = { bg = "NONE" },
-- 					-- LineNr = { fg = "#C0A36E", bg = "NONE" },
-- 					CursorLineNr = { fg = colors.palette.sakuraPink, bg = "NONE" },
-- 				}
-- 			end,
-- 			theme = 'dragon',
-- 		})
-- 		-- vim.cmd("colorscheme NeoSolarized")
-- 		vim.cmd("colorscheme kanagawa-dragon")
-- 		-- vim.keymap.set('n', '<leader>tl', '<cmd>set background=light<cr>')
-- 		-- vim.keymap.set('n', '<leader>td', '<cmd>set background=dark<cr>')
-- 		vim.cmd [[highlight IndentBlanklineContextStart guisp=#FF0000 gui=underline]]
-- 	end
-- }
